/*
LATTICE PATHS

USING PURE RECURSION COUNT THE NUMBER OF UNIQUE PATHS
TO TRAVEL FROM THE TOP LEFT CORNER TO THE BOTTOM RIGHT CORNER
OF A LATTICE OF M X N SQUARES VIA VERTICES. WHEN
MOVING THROUGH THE LATTICE, ONCE CAN ONLY TRAVEL
TO THE ADJACENT CORNER ON THE RIGHT OR DOWN. 

INPUT: M, INTEGER (NUMBER OF ROWS OF SQUARES) 
INPUT: N, INTEGER (NUMBER OF COLUMNS)
OUTPUT: INTEGER, NUMBER OF UNIQUE PATHS FROM 0,0 TO M, N

CONSTRAINTS:


EDGE CASES: 



TEST CASES: 

1. (2,3)

0 __1__2__3
1|__|__|__|
2|__|__|__|

EXPECTED OUTPUT: 10





*/